config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks , only: [:create, :edit, :update, :destroy] do
    member do
      get "complete"
      get "incomplete"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  enum is_complete: {未完了: 0, 完了: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_params, only: [:edit, :update]
  before_action :set_status, only: [:index, :edit]

  def index
    @task = Task.new
    
  end

  def create
    @task = Task.new(post_params)
    # respond_to do |format|
    #   format.html {redirect_to :root}
    #   format.json {render json: @task}
    # end
    if @task.save
      redirect_to root_path
    end
    
  end

  def edit
  
  end

  def update
    if @task.update(post_params)
      redirect_to root_path
    else
      render :new
    end
    
  end

  def destroy
    task = Task.find(params[:id])
    if task.destroy
      redirect_to root_path
    end
  end

  def complete
    task = Task.find(params[:id])
    task.is_complete = "完了"
    if task.save
      redirect_to root_path
    end
  end

  def incomplete
    task = Task.find(params[:id])
    task.is_complete = "未完了"
    if task.save
      redirect_to root_path
    end
  end

  private
  def find_params
    @task = Task.find(params[:id])
  end

  def post_params
    params.require(:task).permit(:body , :is_complete, )
  end

  def set_status
    @tasks_incomplete = Task.all.where(is_complete: "未完了").order(created_at: :desc)
    @tasks_complete = Task.all.where(is_complete: "完了").order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="display-4 pl-5">Simple To Do</p>
  </div>
</div>

<%= form_with(model: @task, local:true, class: "js-form") do |f| %>
  <div class="form-row pb-5">
    <div class="form-group  col-6 offset-2 task-title">
      <%= f.text_field :body, class: "form-control", id: "taskTitle", placeholder: "タスクのタイトル" %>
      <div class="submit-btn">
        <%= f.submit "変更する", class: "btn btn-primary ml-4" %>
      </div>
    </div>
  </div>
<% end %>
<div class="container  task ">
  <div class="row  offset-2">
    <h1>未完了</h1>
  </div>
  <% @tasks_incomplete.each do |task| %>
    <div class=" row incomplete-task offset-2 py-2 border-top border-bottom ">
      <p class="col-7 ">
        <%= task.body %>
      </p>
      <%= link_to "編集", edit_task_path(task.id) ,  class: "col-1 rounded btn btn-light border mr-2", id: "edit-task" %>
      <%= link_to "削除", task_path(task.id),method: :delete, class: "col-1 rounded btn btn-light border mr-2" %>
      <%= link_to "完了する", complete_task_path(task.id), class: "col-2 rounded btn btn-primary "%>
    </div>
  <% end %>
  
</div>
<div class="container  task ">
  <div class="row  offset-2">
    <h1>完了済み</h1>
  </div>
  <% if @tasks_complete.length == 0 %>
    <div class="offset-2 complete-task">
      <p>タスクは登録されていません</p>
    </div>
  <% end %>
  <% @tasks_complete.each do |task| %>
    <div class=" row complete-task offset-2 py-2 border-top border-bottom">
      <p class="col-7 ">
        <%= task.body %>
      </p>
      <%= link_to "編集", edit_task_path(task.id), class: "col-1 rounded btn btn-light border mr-2 edit-btn" %>
      <%= link_to "削除", task_path(task.id),method: :delete, class: "col-1 rounded btn btn-light border mr-2" %>
      <%= link_to "戻す", incomplete_task_path(task.id), class: "col-2 rounded btn btn-primary " %>
    </div>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="display-4 pl-5">Simple To Do</p>
  </div>
</div>

<%= form_with(model: @task, local:true, class: "js-form") do |f| %>
  <div class="form-row pb-5">
    <div class="form-group  col-6 offset-2 task-title">
      <%= f.text_field :body, class: "form-control", id: "taskTitle", placeholder: "タスクのタイトル" %>
      <div class="submit-btn">
        <%= f.submit "タスクを作成", class: "btn btn-primary ml-4" %>
      </div>
    </div>
  </div>
<% end %>
<div class="container  task ">
  <div class="row  offset-2">
    <h1>未完了</h1>
  </div>
  <% if @tasks_incomplete.length == 0 %>
    <div class="row offset-2">
      <p>タスクは登録されていません</p>
    </div>
  <% end %>
  <% @tasks_incomplete.each do |incomplete| %>
    <div class=" row incomplete-task offset-2 py-2 border-top border-bottom ">
      <p class="col-7 ">
        <%= incomplete.body %>
      </p>
      <%= link_to "編集", edit_task_path(incomplete.id) ,  class: "col-1 rounded btn btn-light border mr-2", id: "edit-task" %>
      <%= link_to "削除", task_path(incomplete.id),method: :delete, class: "col-1 rounded btn btn-light border mr-2" %>
      <%= link_to "完了する", complete_task_path(incomplete.id), class: "col-2 rounded btn btn-primary "%>
    </div>
    
  <% end %>
  
</div>
<div class="container  task ">
  <div class="row  offset-2">
    <h1>完了済み</h1>
  </div>
  <% if @tasks_complete.length == 0 %>
    <div class="offset-2 complete-task">
      <p>タスクは登録されていません</p>
    </div>
  <% end %>
  <% @tasks_complete.each do |complete| %>
    <div class=" row complete-task offset-2 py-2 border-top border-bottom">
      <p class="col-7 ">
        <%= complete.body %>
      </p>
      <%= link_to "編集", edit_task_path(complete.id), class: "col-1 rounded btn btn-light border mr-2 edit-btn" %>
      <%= link_to "削除", task_path(complete.id),method: :delete, class: "col-1 rounded btn btn-light border mr-2" %>
      <%= link_to "戻す", incomplete_task_path(complete.id), class: "col-2 rounded btn btn-primary " %>
    </div>
  <% end %>
</div>